name: Keep Streamlit Alive

on:
  schedule:
    # 2시간마다 실행 (UTC 기준)
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -L "https://enig-calculator-vjdpvyntkv3jge3hpfmmzt.streamlit.app" > /dev/null
